Creation of parser.jl, with the parser function writed
remi-garcia/RoadefRenaultBrazil pull request #3
Opened 2019-10-11 18:36 UTC by Jonathan-Fontaine44

Closes #2

2019-10-11 18:51 UTC, remi-garcia requested changes
`Int64`/`Int`
`Array{T, 1}`/`Vector{T}`
`Array{T, 2}`/`Matrix{T}`

I think we should follow the [JuMP style guide](https://www.juliaopt.org/JuMP.jl/stable/style/)

2019-10-12 09:16 UTC, remi-garcia requested changes
Except for the naming style we just discuss after you opened this PR this looks fine for me.

2019-10-12 09:16 UTC, remi-garcia commented on src/parser.jl
> +VEHICLES_FILE_NAME = "vehicles.txt"
Constant/Constants
`CONSTANT_NAME`/`const CONSTANT_NAME`

2019-10-12 09:16 UTC, remi-garcia commented on src/parser.jl
> +    LPRC_rank::Int64 # Si il n'y a pas de LPRC, LPRC_rank = -1
Comment code in English for consistency

2019-10-12 09:16 UTC, remi-garcia commented on src/parser.jl
> +function parser(Instance_name::String, instanceType::String, pathFolder::String="../data/Instances_")
`Instance_name`/`instance_name`
`instanceType`/`instance_type`
`pathFolder`/`path_folder`

2019-10-12 09:16 UTC, remi-garcia commented on src/parser.jl
> +        )
Should be
```Julia
    return Instances(HPRC_rank, LPRC_rank, PCB_rank,
                     nb_paint_limitation,
                     HPRC, LPRC, nb_high, nb_low,
                     HPRC_flag, LPRC_flag, color_code
        )
```

2019-10-14 08:25 UTC, k-fretaud commented
> Int64 -> Int 
May be a good choice (must be check) but I'm not for the Vector/Matrix change

2019-10-14 08:39 UTC, remi-garcia commented
According to [this thread](https://groups.google.com/forum/#!topic/julia-users/qs3lZj7AaY8) we should use `Int` since `Int64` isn't necessary.
After this change and the constant one I'll approve this.

2019-10-14 15:43 UTC, remi-garcia approved these changes

2019-10-16 14:53 UTC, BenoitLoger approved these changes

2019-10-16 14:54 UTC, merged